name: Fix enemy data
description: File a correction on the enemy data
title: "[Fix]: Data for"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        To get the id of the mob look in the log window for dalamud.
  - type: input
    id: mob_id
    attributes:
      label: Mob Id
      description: The id of the mob in game
      placeholder: ex. 5429
    validations:
      required: true
  - type: dropdown
    id: agrotype
    attributes:
      label: What agro type does the mob have
      options:
        - Sight
        - Sound
        - Proximity
        - Boss
    validation:
      required: true
  - type: checkboxes
    id: vulnerabilities
    attributes:
      label: Vulnerabilities for the enemy
      description: What vulnerabilities does the enemy have?
      options:
        - label: Stun
        - label: Heavy
        - label: Slow
        - label: Sleep
        - label: Bind
        - label: Undead
  - type: textarea
    id: text
    attributes:
      label: Additional mob text guide
      description: Is there anything worth telling the player about this mob?