name: Build

on:
  push:
    branches:
      - master

env:
  PUBLIC_NAME: DeepDungeonDex
  SOLUTION_NAME: DeepDungeonDex
  INTERNAL_NAME: DeepDungeonDex
  RELEASE_DIR: D:\a\DeepDungeonDex\DeepDungeonDex\bin\Release\DeepDungeonDex
jobs:
  build:
    runs-on: windows-latest
    if: ${{ (contains(github.event.head_commit.message, '[PR]') || contains(github.event.head_commit.message, '[TEST]')) && !contains(github.event.head_commit.message, '[SKIP]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update project json
        run: |
          $a = Get-Content .\DeepDungeonDex.json -raw | ConvertFrom-Json
          $a.Changelog="${{ steps.version.outputs.changelog }}"
          $a | ConvertTo-Json | Set-Content .\DeepDungeonDex.json
      - name: Output project json
        run: cat DeepDungeonDex.json
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"   
      - name: Build
        run: |
          dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
          dotnet build --configuration Release /p:Version=${{ steps.version.outputs.new_version }}
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - uses: actions/upload-artifact@v2
        with:
          name: PluginRepoZip
          path: ${{ env.RELEASE_DIR }}
          if-no-files-found: error
  pull_request:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        id: download-artifact
        with:
          name: PluginRepoZip
          path: PluginArtifact

      - name: Create pull request
        uses: daemitus/DalamudPluginPR@master
        with:
          token: ${{ secrets.PAT }}
          artifact_path: ${{ steps.download-artifact.outputs.download-path }}
